USE projetomercurio;

CREATE TABLE item (
	IdItem INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	Tipo VARCHAR(100) NOT NULL,
	Nome VARCHAR(100) NOT NULL,
	Quantidade INT NOT NULL);
	
CREATE TABLE pedinte (
	IdPedinte INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	Nome VARCHAR(50) NOT NULL,
	Idade INT NOT NULL,
	DataEntrada DATETIME NOT NULL);

CREATE TABLE pedido (
	IdPedido INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	IdPedinte INT NOT NULL,
	DataPedido DATETIME NOT NULL,
	FOREIGN KEY (IdPedinte) REFERENCES pedinte(IdPedinte));


CREATE TABLE pedidoxitem (
	IdPedidoxItem INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	IdPedido INT NOT NULL,
	IdItem INT NOT NULL,
	FOREIGN KEY (IdPedido) REFERENCES pedido(IDPedido),
	FOREIGN KEY (IdItem) REFERENCES item(IdItem)
);

CREATE TABLE rua(
	IdRua INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	Nome VARCHAR(100) NOT NULL
);

CREATE TABLE ponto(
	Idponto INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	Nome VARCHAR(100) NOT NULL
);

CREATE TABLE pontoxrua (
	IdPontoxRua INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	IdRua INT NOT NULL,
	IdPonto INT NOT NULL,
	FOREIGN KEY (IdRua) REFERENCES rua(IdRua),
	FOREIGN KEY (IdPonto) REFERENCES ponto(IdPonto)
);

CREATE TABLE ligacao (
	IdLigacao INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	IdFocal INT NOT NULL,
	IdProximo INT NOT NULL,
	FOREIGN KEY (IdFocal) REFERENCES ponto(IdPonto),
	FOREIGN KEY (IdProximo) REFERENCES ponto(IdPonto)
);

CREATE TABLE local (
	IdLocal INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	IdPonto INT NOT NULL,
	Nome VARCHAR(100) NOT NULL,
	FOREIGN KEY (IdPonto) REFERENCES ponto(IdPonto)
);

